<?php
/*
 * Copyright 2021 Martin Espericueta <espmartin@espmartin-Inspiron-7786>
 * 
 * This web page is mine :)
 * 
 * 
 */
?>
<!-- The flexible grid (content) -->
<main class="row" id="main-content">
	<article class="side">
    	<h2>Services:</h2>
    	<div class="images images--tall" role="presentation"></div>
    	<p>Enjoy my afordable web site designs, custom made to suite your needs!</p>
		<p>Portfolio sites I've created:</p>
        <ul>
            <li>
				<a href="https://pawtrainingdoneright.com/" target="_blank" rel="noopener noreferrer">
					<span class="portfolio-image" role="img" aria-label="Paw Training Done Right website thumbnail" style="background-image: url('/images/ptdr-th.png')"></span>
				</a>
			</li>
        </ul>
    	<h3>Thank You!</h3>
    	<div class="images images--short" role="presentation"></div>
    	<div class="images images--short" role="presentation"></div>
    	<div class="images images--short" role="presentation"></div>
	</article>
  	<article class="main">
	    <h2>What I Offer!</h2>
	    <div class="images images--tall" role="presentation"></div>
	    <h3>Services &amp; Products</h3>
		<p>Let me create your new website, keeping your target audience in mind, with adhereance to Accessibility, Ease Of Use, &amp; SEO (Search Engine Optimisation) at the forefront of the code!</p>
	    <h4>Here's What I'll Do For You:</h4>
		<ul>
			<li>Unique, hand-coded 5 page website!</li>
			<li><a class="not-normal-link" href="#seo" title="SEO (Search Engine Optimisation) services">SEO (Search Engine Optimisation) services!</a></li>
			<li>Maintenace of your existing website!</li>
		</ul>
    	<h4 id="seo">SEO (Search Engine Optimisation)</h4>
		<p>SEO (Search Engine Optimisation), according to Google's definition, is:</p>
		<blockquote>
			The process of improving the quality and quantity of website traffic to a website or a web page from search engines. SEO targets unpaid traffic rather than direct traffic or paid traffic.
		</blockquote>
		<p>While there is so much more to SEO than that (for example, link building &amp; the &quot;<em>quality</em>&quot; or, &quot;<em>value</em>&quot; of those backlinks), the best place to begin implementing SEO on your website is - from the very start! SEO techniques should be applied to the actual web page's HTML (Hypertext Markup Language) - as it is being written. Yes, SEO can be brought on to an existing website's markup - but by that time in my own experience, when I've seen sites that requested SEO - the code itself <strong>typically</strong> looks like a spagetti mess of machine code &amp; JavaScripting that will <em>have to be re-written</em> to include the optimizations - <strong><em>What A Mess!</em></strong></p>
		<p>Typically as well, site's that are created using a &quot;free website builder&quot; service are, in my opinion, the worse to do so! The code generated by those free services is usually horrid! <strong>THEN</strong> those <em>free</em> services will &quot;offer&quot; coupons to use with Google AdWords (ie: &quot;Sponsored Results&quot; in the SERPs.</p>
		<p>But Search Engine Optimization will allow a serch engine's automatic 'bots &amp; Search Engine Spiders such a clean &amp; ootimized code to read through. No longer will a SE (Search Engine) have to read houndreds of lines of machine code - to get to minimal relevant content. See, with a custom website that has been built from hand (hand-coded HTML/CSS), will give those SE's exactly what they need to serve their users relevant content!</p>
		<p>Please feel free to submit the form below to receive information &amp; a price quote today!</p>

	    <div class="images images--tall" role="presentation"></div>
		<div class="container">
			<form id="contact-form" method="post" action="/contact/get.php" autocomplete="on">
				<label for="name">Full Name</label>
    			<input type="text" id="name" name="name" placeholder="Your name.." required>
				<label for="email">Email address</label>
			    <input type="email" id="email" name="email" placeholder="Your email address.." required>
				<label for="phone">Phone number</label>
			    <input type="tel" id="phone" name="phone" placeholder="Your phone number.." required>
    			<label for="services">Services</label>
    			<select id="services" name="services" required>
      				<option value="">Choose an option</option>
      				<option value="creation">Website Creation</option>
      				<option value="maintenance">Maintain Existing Site</option>
      				<option value="seo">Search Engine Optimisation</option>
    			</select>

    			<label for="subject">Subject</label>
    			<textarea id="subject" name="subject" class="textarea-tall" placeholder="Write something.." required></textarea>

			    <div class="g-recaptcha brochure__form__captcha" data-sitekey="6Ld14acUAAAAAJkARsG15-a5f6_Nx9QSxp1Ejllk"></div>
				<button type="submit">Submit</button>
				<button type="reset">Clear</button>
  			</form>
        </div>

    	<h2>Are you looking for a &quot;One-Stop Shop&quot;?</h2>
    	<h3>Other Services</h3>
    	<div class="images images--tall" role="presentation"></div>
    	<p>I also offer our webmaster services in the Audio/Video area. If your business or church, or whaterver you're doing, requires live online streaming, I can help support that for you! From basic setup, to auditing, to just giving our recommendations on what tools, services you'll need to get your live streams flowing!</p>
	</article>
</main>